apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuarios-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usuarios
  template:
    metadata:
      labels:
        app: usuarios
    spec:
      containers:
        - name: usuarios
          image: IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "eks"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mariadb://40.233.27.238:3307/auth_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "app_user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "appSa456."
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-service:8765/eureka/"
            # Kafka MSK
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: b-1.kafkap2sa.uqqw98.c10.kafka.us-east-1.amazonaws.com:9094,b-2.kafkap2sa.uqqw98.c10.kafka.us-east-1.amazonaws.com:9094
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: usuarios-group
            - name: SPRING_KAFKA_PRODUCER_ACKS
              value: all
            - name: SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET
              value: earliest
            - name: MSK_TRUSTSTORE_PASSWORD
              value: "changeit"
          volumeMounts:
            - name: msk-truststore
              mountPath: /app
              readOnly: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 10
      volumes:
        - name: msk-truststore
          secret:
            secretName: msk-truststore
            items:
              - key: truststore.jks
                path: truststore.jks